export const GET_LOGIN_DETAILS = "GET_LOGIN_DETAILS";

export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";

export const GET_FORGET_DETAILS ="GET_FORGET_DETAILS"

export const POST_FORGET = "POST_FORGET";
export const POST_FORGET_ERROR = "POST_FORGET_ERROR";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";



// export const GET_ALL_MASTER_DATA = "GET_ALL_MASTER_DATA";

export const GET_BATCH_VERIFICATION = "GET_BATCH_VERIFICATION";

export const GET_USER = "GET_USER"

export const UPDATE_STATUS ="UPDATE_STATUS"
export const OTP_VERIFY = "OTP_VERIFY"
export const OTP_VERIFY_ERROR = "OTP_VERIFY_ERROR"
export const LOGOUT_DATA = "LOGOUT_DATA"
